name:                upload
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.schibsted.io/christopher-kolstad/servant-upload
license:             BSD3
author:              Christopher Kolstad
maintainer:          christopher.kolstad@finn.no
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.9 && < 5
  - filepath 

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - aeson
  - wai
  - servant >= 0.13.0.1 && < 0.14
  - servant-server >= 0.13.0.1 && < 0.14
  - bytestring
  - text
  - strict
  - prometheus-client
  - clock
  - time
  - http-client
  - servant-auth >= 0.3.2.0 && < 0.4
  - servant-auth-server >= 0.3.2.0 && < 0.4
  - jwt
  - containers
  - scientific
  - optparse-applicative
  

executables:
  upload-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - upload

tests:
  upload-test:
    main: Specs.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - upload
      - hspec >= 2.4
      - directory >= 1.3
      - aeson
      - bytestring
      - vault
      - wai
      - case-insensitive
      - http-types